#
# Usage:
#
#   docker build -f Dockerfile.alpine -t alpine .
#   docker run -d alpine
#

FROM alpine:latest

RUN printf '\n\
echo running $0\n\
\n\
while [ true ] \n\
do\n\
sleep 10000\n\
done\n\
' >/docker-entrypoint.sh

ENTRYPOINT ["/bin/sh","/docker-entrypoint.sh"]
